apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1-deploy
spec:
  replicas: 6
  selector:
    matchLabels:
      app: demo1
  template:
    metadata:
      labels:
        app: demo1
    spec:
      containers:
      - name: demo1-pod
        image: adamdemos/demo1:v1
        ports:
        - containerPort: 80
